#Jay Pandit 
#lab10

lab10: lab10.o ProcessInput.o Redirection.o   ParseLine.o  RunExternalCommand.o
		gcc lab10.o ParseLine.o ProcessInput.o Redirection.o RunExternalCommand.o -o lab10 -lm -Wall

lab10.o: lab10.c lab9_10.h
		 gcc -c lab10.c -lm -Wall

ParseLine.o: ParseLine.c lab9_10.h
			gcc -c ParseLine.c -lm -Wall 

ProcessInput.o: ProcessInput.c lab9_10.h
				gcc -c ProcessInput.c -lm -Wall 

Redirection.o: Redirection.c lab9_10.h
				gcc -c Redirection.c -lm -Wall

RunExternalCommand.o: RunExternalCommand.c lab9_10.h
					  gcc -c RunExternalCommand.c -lm -Wall
